### PR TITLE
Elevation

### PR DESCRIPTION
**Pull request by darienyoder**
Levels can now have slopes marked by gradients from light-green to dark-green. Sand and water are now handled through this system, rather than the obstacle system.

### CODE REVIEW

**Comment by clickyquack** [comment]
When I try to run the elevation branch on its own, the settings do not work. Also, when the ball bounces, it loses a decent portion of its momentum, which it did not do before. I personally prefer that it keeps all of its momentum, as regardless of how realistic it may or may not be, I feel that this simply makes it more fun (although we might have to decide on this as a group if it's controversial. Also, I expect level 5 will no longer be beatable in one stroke with this change when it is designed to). Also also, I opened a separate testing branch to see what would happen if I let it automatically merge to main, but when I try to run it the buttons for starting the game, level select, and opening settings are all gone. I have not yet been able to find what is causing this, but regardless, it shows that this will have to be manually merged to some extent.

**Comment by darienyoder** [comment]
Thanks for catching that. I'll make an issue for for the settings button. The elevation branch doesn't have the newest changes like menu buttons, so I may need to merge those features into the branch first. As for bounces losing momentum, I will put it back the way it was, though I think we should ask the rest of the group and our stakeholder for more opinions, since I think it's better losing at least a little bit of momentum.

**Comment by darienyoder** [comment]
Canvases have been placed behind the settings menu so that they do not obstruct the interface. I left some test obstacles in the first level for ease of reviewing; they can be removed after merging.

**Comment by clickyquack** [comment]
The camera follow mode causes the visuals of the elevation (including any obstacles tied to it) to move _with_ the ball, although gameplay-wise the ball still behaves as though there is sand and water and elevation in the same places in the test level, so that's a purely visual bug. Another thing worth noting is that the level is different based on the resolution of the browser (specifically the height relative to the width, not the overall resolution like 1080p vs 720p). Also resizing the window breaks things visually (even more than was already pointed out in #129 ). But maybe these are unimportant enough that we can still merge these now and fix in a later sprint (or maybe just leave as is as we're getting close to the end)? What do you think? Other than that it seems great, I especially like the way sand affects the ball now, it feels more like what you would expect a sand trap to do. The visual changes to sand, water, and the green are nice. Also I played around with adding hills/valleys/obstacles in level-data.js and it seems really good functionally. Anyway let me know if you want to try to fix any of the bugs before I try resolving the conflicts that would be involved in a merge.

**Comment by darienyoder** [comment]
I think it'd be best to merge now so that we can start building levels with these new features. Since the current bugs are exclusively visual we can make a priority to fix them, but I don't think we should wait until the branch is totally perfect before we merge, as there are no gameplay regressions that would interfere with the implementation of unrelated features.

**Pull request merged**
